version: '3'
services:
  mysqlmaster:
    image: mysql:5.7.15
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./db/data/mysql-master:/var/lib/mysql/
      - ./db/config/mysql-master:/etc/mysql/conf.d/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/dump.sql:/go_app_db_dump.sql

    networks:
      replication:
        aliases:
          - mysqlmaster
    ports:
      - "3306:3306"

  mysqlslave_1:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./db/data/mysql-slave-1:/var/lib/mysql/
      - ./db/dump.sql:/docker-entrypoint-initdb.d/go_app_db_dump.sql
      - ./db/config/mysql-slave/slave_1.cnf:/etc/mysql/conf.d/slave.cnf
    networks:
      - replication
    ports:
      - "3308:3306"

  mysqlslave_2:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./db/data/mysql-slave-2:/var/lib/mysql/
      - ./db/config/mysql-slave/slave_2.cnf:/etc/mysql/conf.d/slave.cnf
    networks:
      - replication
    ports:
      - "3309:3306"
  
  mysqlconfigure:
    image: mysql:5.7.15
    environment:
      - "MYSQL_SLAVE_PASSWORD=root"
      - "MYSQL_MASTER_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    volumes:
      - ./db/mysql_connector.sh:/tmp/mysql_connector.sh
    command: /bin/bash -x /tmp/mysql_connector.sh
    networks:
      - replication

  go_nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
      - ./templates:/templates
      - ./assets:/assets
      - ./pain:/pain
    command: >
      bash -c "nginx -g \"daemon off;\"; ./pain"
    networks:
      - replication
    links:
      - mysqlmaster
    depends_on:
      - mysqlmaster
     
networks:
  replication:


    # CHANGE MASTER TO
    #    MASTER_HOST='mysqlslave_1',
    #    MASTER_USER='repl',
    #    MASTER_PASSWORD='repl',
    #    MASTER_LOG_FILE='mysql-bin.000009',
    #    MASTER_LOG_POS= 500;