version: '3'
services:
  go_nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./dudes/nginx/logs:/var/log/nginx
      - ./dudes/nginx/dev.conf:/etc/nginx/nginx.conf
      - ./dudes/templates:/templates
      - ./assets:/assets
      - ./dudes/boil:/boil
      - ./dudes/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      - mservises
      - replicated_pg_cluster
    environment: 
      DB_MASTER_URL: "postgres://postgres:postgres@pg-master/go_app_db?sslmode=disable"
      DB_SLAVE_URL: "postgres://postgres:postgres@pg-slave/go_app_db?sslmode=disable"
    links: 
      - timing_ms 

  timing_ms:
    image: ubuntu
    restart: always
    ports:
      - "90:3030"
    volumes:
      - ./timing/main:/main
    command: >
      bash -c "./main"
    networks:
      - mservises
      - replicated_pg_cluster
    environment: 
      DB_MASTER_URL: "postgres://postgres:postgres@pg-master/timing_db?sslmode=disable"
      DB_SLAVE_URL: "postgres://postgres:postgres@pg-slave/timing_db?sslmode=disable"

networks:
  replicated_pg_cluster:
    external: true
  mservises:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16